# -*- coding: utf-8 -*-
"""SaglikGPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12i_sLwz45chwFgL2mpreDZtspWNDsYrB
"""

import streamlit as st
import requests

OPENROUTER_API_KEY = "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"

def sadeleştir_openrouter(metin):
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }

    data = {
        "model": "openai/gpt-3.5-turbo",   # Aynı model, sadece prompt değişti
        "messages": [
            {"role": "system", "content": "Sen bir tıbbi sadeleştirme asistanısın."},
            {"role": "user", "content": f"Verilen tıbbi metni hasta yakınına anlatır gibi Türkçe, açık ve sade bir dille açıkla. Tanı koyma, tedavi önerme.\n\nMetin:\n{metin}\n\nAçıklama:"}
        ],
        "temperature": 0.6,
        "max_tokens": 600
    }

    response = requests.post("https://openrouter.ai/api/v1/chat/completions", headers=headers, json=data)

    if response.status_code == 200:
        return response.json()['choices'][0]['message']['content']
    else:
        return f"Error: {response.text}"

# Streamlit Web Arayüzü
st.set_page_config(page_title="SağlıkGPT", page_icon="🧠")
st.title("🧠 SağlıkGPT - Tıbbi Metin Sadeleştirici")

st.write("Tıbbi bir metni buraya yapıştırın, biz de size sade, anlaşılır ve Türkçe bir açıklama sunalım!")

# Kullanıcıdan giriş alınır
tibbi_metin = st.text_area("🔍 Tıbbi Metin:", height=200)

# Butona basınca çalışır
if st.button("Sadeleştir"):
    if tibbi_metin.strip() == "":
        st.warning("Lütfen bir metin girin.")
    else:
        with st.spinner("Sadeleştiriliyor..."):
            cevap = sadeleştir_openrouter(tibbi_metin)
        st.success("Sadeleştirme Tamamlandı!")
        st.write("### 📄 SağlıkGPT'nin Açıklaması:")
        st.write(cevap)
